
// Adopt Gradle 10 semantics early: fail fast if build logic relies on implicit lookup
// of properties or methods in parent projects.
enableFeaturePreview("NO_IMPLICIT_LOOKUP_IN_PARENT_PROJECTS")

rootProject.name = 'bosk'

include 'bosk-annotations'
include 'bosk-boson'
include 'bosk-core'
include 'bosk-graphql'
include 'bosk-jackson'
include 'bosk-junit'
include 'bosk-logback'
include 'bosk-mongo'
include 'bosk-opentelemetry'
include 'bosk-spring-boot'
include 'bosk-sql'
include 'bosk-testing'
include 'boson'
include 'example-hello'
include 'lib-testing'
