services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP over gRPC
      - "4318:4318"    # OTLP over HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
