spring.application.name=hello
server.port=1740
bosk.web-api.maintenance.access=UNSECURED
bosk.web-api.maintenance.path=/bosk/state

# Now that we use this in unit tests, quiet down the logging
spring.main.banner-mode=off
